---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: spring-petclinic
spec:
  rules:
    - host: petclinic.withtanzu.com
      http:
        paths:
          - backend:
              serviceName: api-gateway
              servicePort: 8080
