---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: spring-petclinic
data:
  APP_CUSTOMERS_URI: "http://customers:8080"
  APP_VETS_URI: "http://vets:8080"
  APP_VISITS_URI: "http://visits:8080"
  SPRING_PROFILES_ACTIVE: mysql
  SERVER_PORT: "8080"
