---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: spring-petclinic
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: customers
  namespace: spring-petclinic
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: customers
---
apiVersion: v1
kind: Service
metadata:
  name: vets
  namespace: spring-petclinic
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: vets
---
apiVersion: v1
kind: Service
metadata:
  name: visits
  namespace: spring-petclinic
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: visits
