---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
  namespace: spring-petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: api-gateway
